# Generated by Django 4.2.7 on 2024-03-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0011_order_syc_skc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='so_rep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số rep'),
        ),
    ]
