# Generated by Django 4.2.7 on 2024-03-12 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0012_order_so_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='so_luong',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='order',
            name='so_rep',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số rep'),
        ),
    ]
