# Generated by Django 4.2.7 on 2024-03-12 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0013_order_so_luong_alter_order_so_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='so_luong',
        ),
    ]
