# Generated by Django 4.2.7 on 2024-03-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nobarcode', '0014_remove_order_so_luong'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinfo',
            name='drawing_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Loại bản vẽ'),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='inspection',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kiểm tra'),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='make_black',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Làm đen'),
        ),
        migrations.AddField(
            model_name='requestinfo',
            name='usually_or_urgent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bản vẽ thường gấp'),
        ),
    ]
